# Generated by Django 5.2.4 on 2026-07-29 21:39

import apps.orders.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Creado'), ('SEARCHING', 'Buscando repartidor'), ('ACCEPTED', 'Aceptado'), ('IN_TRANSIT_TO_ORIGIN', 'En camino al origen'), ('ARRIVED_ORIGIN', 'Llegó al origen'), ('PICKED_UP', 'Recogido'), ('IN_TRANSIT_TO_DESTINATION', 'En camino al destino'), ('NEAR_DESTINATION', 'Cerca del destino'), ('DELIVERED', 'Entregado'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado'), ('FAILED', 'Fallido')], default='CREATED', max_length=30)),
                ('order_type', models.CharField(choices=[('IMMEDIATE', 'Entrega inmediata'), ('SCHEDULED', 'Entrega programada')], default='IMMEDIATE', max_length=20)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('origin_address', models.CharField(max_length=255)),
                ('origin_latitude', models.FloatField()),
                ('origin_longitude', models.FloatField()),
                ('origin_notes', models.TextField(blank=True, null=True)),
                ('destination_address', models.CharField(max_length=255)),
                ('destination_latitude', models.FloatField()),
                ('destination_longitude', models.FloatField()),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('destination_notes', models.TextField(blank=True, null=True)),
                ('weight_kg', models.FloatField(default=1.0)),
                ('dimensions_cm', models.CharField(blank=True, max_length=50, null=True)),
                ('packages_count', models.IntegerField(default=1)),
                ('declared_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_fragile', models.BooleanField(default=False)),
                ('needs_cold_chain', models.BooleanField(default=False)),
                ('is_dangerous', models.BooleanField(default=False)),
                ('requires_signature', models.BooleanField(default=False)),
                ('package_photo_1', models.ImageField(blank=True, null=True, upload_to='orders/packages/')),
                ('package_photo_2', models.ImageField(blank=True, null=True, upload_to='orders/packages/')),
                ('vehicle_type', models.CharField(choices=[('MOTO', 'Motocicleta'), ('CAR', 'Automóvil'), ('VAN', 'Camioneta'), ('TRUCK', 'Camión')], default='MOTO', max_length=20)),
                ('distance_km', models.FloatField(default=0.0)),
                ('estimated_duration_min', models.FloatField(default=0.0)),
                ('base_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('surcharges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('driver_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_method', models.CharField(choices=[('CARD', 'Tarjeta'), ('TRANSFER', 'Transferencia'), ('CASH', 'Efectivo'), ('WALLET', 'Wallet'), ('CREDITS', 'Créditos')], default='CARD', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('otp_code', models.CharField(default=apps.orders.models.generate_otp, max_length=6)),
                ('pod_location_photo', models.ImageField(blank=True, null=True, upload_to='orders/pod/')),
                ('pod_package_photo', models.ImageField(blank=True, null=True, upload_to='orders/pod/')),
                ('pod_latitude', models.FloatField(blank=True, null=True)),
                ('pod_longitude', models.FloatField(blank=True, null=True)),
                ('pod_timestamp', models.DateTimeField(blank=True, null=True)),
                ('pod_recipient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('pod_recipient_id', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
