# Generated by Django 5.2.4 on 2026-09-09 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='scheduled_pickup_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('IMMEDIATE', 'Entrega inmediata'), ('EXPRESS', 'Entrega express'), ('SCHEDULED', 'Entrega agendada')], default='IMMEDIATE', max_length=20),
        ),
    ]
