# Generated by Django 5.2.4 on 2026-07-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialSurgeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('multiplier', models.FloatField(default=1.2)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('MOTO', 'Motocicleta'), ('CAR', 'Automóvil'), ('VAN', 'Camioneta'), ('TRUCK', 'Camión')], max_length=20, unique=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=5000.0, max_digits=10)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=1200.0, max_digits=10)),
                ('price_per_minute', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=2, default=6000.0, max_digits=10)),
                ('max_weight_kg', models.FloatField(default=20.0)),
                ('max_volume_m3', models.FloatField(default=0.1)),
            ],
        ),
    ]
